require('../sass/main.sass');
require('../sass/section-main.sass');
require('../sass/soft.sass')
require('../sass/love.sass');
require('../sass/video.sass');
require('./section-main.js');
require('./love.js');
require('./soft.js');
require('./video.js');
